### ISSUE TITLE
How many times are solutions evaluated before inserting into the archive?

### ISSUE THREAD

**Issue by btjanaka** [ollenilsson19/PGA-MAP-Elites#1]
Hi @ollenilsson19! This is a great project. I am wondering, how many times do you evaluate a policy before inserting it into the archive? From reading the paper and looking through some of the code, it seems there is only a single evaluation. However, I found this confusing, because the environments are stochastic, and as such, they would require multiple evaluations. Is there some way you get around this?

Thanks!

**Comment by ollebompa** [comment]
Hi @btjanaka!

Sorry for the delayed response. 

Solutions are only evaluated once for addition to the archive. This is partly because of necessity due to our resources not being able run multiple evaluations of each solution. The QDgym tasks are quite resource demanding as each evaluation takes many costly simulation steps.

Of course this single evaluation needs to be representative of the expected or average behavior a solution is likely to exhibit. We found that PGA-MAP-Elites usually learns robust enough behaviors on the QDgym tasks that averaging over multiple evaluations does not change fitness and behavior classification much. This is in stark contrast to "standard" MAP-Elites which requires averaging. We talk about this difference in the paper and also try to show it with the Fitness Difference plot that tracks the difference between the single evaluation and the average over 10 evaluations for the current fittest solution in the archive. Of course tracking this difference for all solutions would be better, but then we'd run into resource issues again.

Also note that our evaluation of the robustness of PGA-MAP-Elites is in no way comprehensive, as this is not the main focus of the paper, and is mainly used to show that PGA-MAP-Elites is much less sensitive than "standard" MAP-Elites.

I hope this answered your query.

**Comment by btjanaka** [comment]
Hi @ollenilsson19, thanks for the insightful response! I'll post again if I have any followup questions.
